version: '3.8'

services:
  my-db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: goormthon
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - goorm-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - goorm-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE_KAFKA:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENERS: INSIDE_KAFKA://kafka:9093
      KAFKA_LISTENER_INTERCEPTOR_CLASSES: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE_KAFKA
      KAFKA_LISTENER_NAME_EXTERNAL: OUTSIDE_KAFKA
      KAFKA_LISTENER_PORT_INTERNAL: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - goorm-network

  app:
    build: .
    depends_on:
      my-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - goorm-network
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/goormthon
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234


networks:
  goorm-network:
    driver: bridge
